openapi: 3.0.0
info:
    title: User Authentication and Settings API
    version: 1.0.0
    description: API for user authentication and managing user settings

servers:
    - url: https://test-server.skillstruck.com/settings
      description: Test server

paths:
    /login:
        post:
            summary: Authenticate user
            description: Accepts a username and password and authenticates the user if correct. Sets an authentication cookie.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                            required:
                                - username
                                - password
            responses:
                '200':
                    description: Successfully authenticated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '400':
                    description: Incorrect credentials

    /logout:
        get:
            summary: Logout user
            description: Removes the authentication cookie
            responses:
                '204':
                    description: Successfully logged out

    /user:
        get:
            summary: Get user data
            description: Returns a JSON object containing data for the current authenticated user
            responses:
                '200':
                    description: Successfully retrieved user data
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '401':
                    description: User not authenticated

        post:
            summary: Update user settings
            description: Update settings for the current authenticated user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                settings:
                                    type: object
                                    properties:
                                        enablePaste:
                                            type: boolean
                            required:
                                - settings
            responses:
                '200':
                    description: Successfully updated user settings
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '400':
                    description: Invalid request format
                '401':
                    description: User not authenticated

components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                username:
                    type: string
                settings:
                    type: object
                    properties:
                        enablePaste:
                            type: boolean
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: session

security:
    - cookieAuth: []
